# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-08 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('poster', models.CharField(max_length=20)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('reply_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
