# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-08 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('poster', models.CharField(max_length=20)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
